stages:
  preprocess:
    cmd: python preprocessing.py
    deps:
      - bank-full.csv
    outs:
      - preprocessed_bank_data.csv

  exploration:
    cmd: python explore.py
    deps:
      - preprocessed_bank_data.csv
      - X_train_encoded.csv
      - X_test_encoded.csv
      - y_train.csv
      - y_test.csv
    outs:
      - exploration_result.txt

  train:
    cmd: python train.py
    deps:
      - data/X_train_encoded.csv
      - data/y_train.csv
    outs:
      - trained_model.pkl

  evaluate:
    cmd: python evaluate.py
    deps:
      - data/X_test_encoded.csv
      - data/y_test.csv
      - trained_model.pkl
    outs:
      - evaluation_result.txt
